# 根路径配置
server:
  port: 9022
  servlet:
    context-path: /${spring.application.name}
  # undertow配置
  # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
  undertow:
    io-threads: 4
  # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
  # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
  # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
#    buffers-per-region: 1024
  # 是否分配的直接内存
    direct-buffers: true

# 监控点端口
management:
  server:
    port: 6022
    servlet:
      context-path: /
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  # 数据库地址
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.4.164:3306/flowable-online?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Bomc@4.164

flowable:
  #关闭定时任务JOB
  async-executor-activate: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@10.1.12.30:8761/eureka
    enabled: true

logging:
  config: classpath:log4j2-dev.xml